### ISSUE TITLE
Cannot read property 'email' of undefined

### ISSUE THREAD

**Issue by vipinlahoti** [xavcz/nova-wires#2]
Im getting an error as below,,

Exception in defer callback: TypeError: Cannot read property 'email' of undefined
at WiresNewSendEmailAsync (packages/xavcz:nova-wires/lib/callbacks.js:58:40)
at packages/nova:lib/lib/modules/callbacks.js:92:18
at Array.forEach (native)
at packages/nova:lib/lib/modules/callbacks.js:90:17
at [object Object]._.extend.withValue (packages\meteor.js:1122:17)
at packages\meteor.js:445:45
at runWithEnvironment (packages\meteor.js:1176:24)

and unable to resolve it.

**Comment by xavxyz** [comment]
Hey @vipinlahoti!

The error comes from: https://github.com/xavcz/nova-wires/blob/master/lib/callbacks.js#L62

At the moment, you don't have an "easy way" to send an email to another user, meaning you have to manually add the `recipientId` (recipient userId) either:
- by hand directly in the field
- hide the field & create a sync callback (example: https://github.com/dominictracey/trn-core/blob/master/lib/custom_fields.js#L209-L214 & https://github.com/dominictracey/trn-core/blob/master/lib/callbacks.js#L38-L48)
- create a custom component that grabs the recipient Id from an autocompletion list (#1) or maybe from some params in the url if your are on a user's profile. 

Happy hacking!

**Comment by xavxyz** [comment]
I've added a note in the readme about that, thanks for the heads up 💯
